import {
	Inbox,
	FileText,
	ClipboardList,
	Users,
	Languages,
	LifeBuoy,
	Settings,
	LogOut,
	PanelLeftClose,
	PanelLeftOpen,
	ChevronDownIcon,
	PlugIcon,
	KeyRoundIcon,
	Building2Icon,
	ShieldCheckIcon,
	ChevronRightIcon,
	ChevronUpIcon,
} from 'lucide-react-native';

export {
	Inbox as RequisicoesIcon,
	FileText as OrcamentoIcon,
	ClipboardList as OrdemServicoIcon,
	Users as ClientesIcon,
	Languages as TradutoresIcon,
	LifeBuoy as SuporteIcon,
	Settings as ConfiguracoesIcon,
	LogOut as SairIcon,
	PanelLeftClose as FecharIcon,
	PanelLeftOpen as AbrirIcon,
	ChevronDownIcon as ChevronDown,
	ChevronRightIcon as ChevronRight,
	ShieldCheckIcon as AdminIcon,
	Building2Icon as EmpresaIcon,
	KeyRoundIcon as PermissoesIcon,
	PlugIcon as IntegracoesIcon,
	ChevronUpIcon as ChevronUp,
};
