ALTER TYPE statusenum ADD VALUE IF NOT EXISTS 'REPROVED';

ALTER TABLE request
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reproved_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reproval_reason VARCHAR(500);
