"""Write Pact files without losing interactions generated by other test modules."""

from __future__ import annotations

import json
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any


def _interaction_key(interaction: dict[str, Any]) -> str:
    request = interaction.get("request", {})
    return json.dumps(
        {
            "description": interaction.get("description"),
            "providerStates": interaction.get("providerStates", []),
            "request": request,
        },
        sort_keys=True,
        separators=(",", ":"),
    )


def merge_pact_files(generated_path: Path, pact_path: Path) -> None:
    """Merge a generated Pact into the destination, replacing only same interactions."""
    generated = json.loads(generated_path.read_text(encoding="utf-8"))
    existing = (
        json.loads(pact_path.read_text(encoding="utf-8"))
        if pact_path.exists()
        else {**generated, "interactions": []}
    )

    interactions = {
        _interaction_key(interaction): interaction
        for interaction in existing.get("interactions", [])
    }
    interactions.update(
        {
            _interaction_key(interaction): interaction
            for interaction in generated.get("interactions", [])
        }
    )
    existing["interactions"] = list(interactions.values())
    existing.setdefault("consumer", generated.get("consumer"))
    existing.setdefault("provider", generated.get("provider"))
    existing["metadata"] = generated.get("metadata", existing.get("metadata", {}))
    pact_path.parent.mkdir(parents=True, exist_ok=True)
    pact_path.write_text(json.dumps(existing, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_pact(pact: Any, pact_dir: Path) -> None:
    """Generate a Pact in isolation, then merge it into the shared Pact file."""
    with TemporaryDirectory() as temporary_dir:
        temporary_path = Path(temporary_dir)
        pact.write_file(temporary_path)
        generated_files = list(temporary_path.glob("*.json"))
        if len(generated_files) != 1:
            raise RuntimeError("Pact writer must generate exactly one JSON file")
        generated_path = generated_files[0]
        destination = pact_dir / generated_path.name
        merge_pact_files(generated_path, destination)
